# run the following command to encode your password for DEV :
# echo -n "YOUR_PASSWORD" | base64
---
apiVersion: v1
kind: Secret
metadata:
  name: govee
  labels:
    app: govee2mqtt
data:
  # This value is base64-encoded. Do not use this password in production!
  govee-email: YOUR_BASE64_ENCRYPTED_PASSWORD
  govee-password: YOUR_BASE64_ENCRYPTED_PASSWORD
  govee-api-key: YOUR_BASE64_ENCRYPTED_PASSWORD
  mqtt-password: YOUR_BASE64_ENCRYPTED_PASSWORD
