apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-mosquitto-conf
  labels:
    app: mqtt
data:
  mosquitto.conf: |
    listener 1883
    persistence true
    persistence_location /mosquitto/data
    persistence_file mosquitto.db
    autosave_interval 60
    password_file /mosquitto/config/mosquitto.passwd
    allow_anonymous false
  mosquitto.passwd: |
    mqtt_user:$6$10z0nozQfUdvMqq7$ejK3JtC6sf8lQ2JAlPD/vvgrG8dtnj2wXaDEj8mn/f2pGEuijWDHEASmnRIz5xzFpNuvMNPJwZ8jOYi6oQupNw==

---
apiVersion: v1
kind: Service
metadata:
  name: mqtt
spec:
  ports:
  - name: port1883
    protocol: TCP
    port: 1883
    targetPort: 1883
    nodePort: 31883
  selector:
    app: mqtt
#  type: LoadBalancer
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mqtt
  name: mqtt-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt
  template:
    metadata:
      labels:
        app: mqtt
    spec:
#      initContainers:
#      - name: volume-mount-hack
#        image: busybox
#        imagePullPolicy: IfNotPresent
##        command: ["sh", "-c", "chown -R 1883:1883 /mosquitto"]
#        command: ["sh", "-c", "sleep 1"]
##        volumeMounts:
##        - name: data-volume
##          mountPath: /mosquitto/data/mosquitto.db
      containers:
      - image: eclipse-mosquitto
        name: mqtt
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 1883
          - containerPort: 9001
        volumeMounts:
          - name: config-file
            mountPath: /mosquitto/config
          - name: data-volume
            mountPath: /mosquitto/data
#            subPath: mosquitto #/nfs/k8sdata/mosquitto
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
        fsGroup: 1883
        runAsGroup: 1883
        runAsUser: 1833
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: pvc-mqtt
        - name: config-file
          configMap:
            name: cm-mosquitto-conf 
