apiVersion: networking.k8s.io/v1
# the working example below demonstrates a sub-path URL. Included (and commented out) is a sub-domain example too
kind: Ingress
metadata:
  name: mysite-grafana-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - secretName: mysite-grafana-tls
      hosts:
        - YOUR-DOMAIN-GOES-HERE.com
#        - grafana.YOUR-DOMAIN-GOES-HERE.com
  rules:
  - host: YOUR-DOMAIN-GOES-HERE.com
    http:
      paths:
        - path: /grafana
          pathType: Prefix
          backend:
            service:
              name: grafana
              port:
                number: 3000

#  - host: grafana.YOUR-DOMAIN-GOES-HERE.com
#    http:
#      paths:
#        - path: /
#          pathType: Prefix
#          backend:
#            service:
#              name: grafana
#              port:
#                number: 3000
