apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  labels:
    app: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      hostNetwork: true
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: pvc-home-assistant
      - name: music-volume
        hostPath:
          path: /home/pi/Music
      - name: dev-usb0
        hostPath:
          path: /dev/ttyACM0
      - name: dev-ama0
        hostPath:
          path: /dev/ttyAMA0
#      - name: dev-snd
#        hostPath:
#          path: /dev/snd
      containers:
      - name: home-assistant
        image: homeassistant/raspberrypi4-homeassistant:stable
#        imagePullPolicy: IfNotPresent
        imagePullPolicy: Always
#        env:
#          - name: TZ
#            value: Europe/London
        volumeMounts:
        - name: music-volume
          mountPath: /config/www/media
        - name: data-volume
          mountPath: /config
        - name: dev-usb0
          mountPath: "/dev/ttyACM0"
        - name: dev-ama0
          mountPath: "/dev/ttyAMA0"
#        - name: dev-snd
#          mountPath: "/dev/snd" 
        livenessProbe:
            tcpSocket:
              port: 8123
            initialDelaySeconds: 60
            periodSeconds: 30
            failureThreshold: 6
            timeoutSeconds: 10
        readinessProbe:
            tcpSocket:
              port: 8123
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 5
            timeoutSeconds: 10
        securityContext:
          privileged: true
      restartPolicy: Always
      
