---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant-service
  labels:
    app: home-assistant
#  annotations:
#    metallb.universe.tf/address-pool: default
spec:
  selector:
    app: home-assistant
  type: NodePort
  ports:
    - protocol: TCP
      port: 8123
      targetPort: 8123
      nodePort: 31123

---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  labels:
    app: home-assistant
spec:
  selector:
    app: home-assistant
  externalTrafficPolicy: Local
  ports:
  - name: ha
    port: 80
    protocol: TCP
    targetPort: 8123
  type: LoadBalancer
#  clusterIP: None



