apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mqtt
  name: mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt
  template:
    metadata:
      labels:
        app: mqtt
    spec:
      securityContext:
        runAsNonRoot: true
        fsGroup: 1883
        runAsGroup: 1883
        runAsUser: 1883
      containers:
      - image: eclipse-mosquitto
        name: mqtt
        imagePullPolicy: Always
        ports:
          - containerPort: 1883
          - containerPort: 9001
        volumeMounts:
          - name: config-file
            mountPath: /mosquitto/config/mosquitto.conf
            subPath: mosquitto.conf
          - name: config-file
            mountPath: /mosquitto/config/mosquitto.passwd
            subPath: mosquitto.passwd
          - name: data-volume
            mountPath: /mosquitto/data
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: pvc-mqtt
        - name: config-file
          configMap:
            name: cm-mosquitto-conf
            defaultMode: 0600
