# replace  192.168.1.15 with the fixed IP of your NFS server
# replace  /home/pi/nfs/k8sdata with the path to your NFS server folder

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mqtt
spec:
  capacity:
    storage: 20M
  accessModes:
    - ReadWriteOnce   
  nfs:
    path: /home/pi/nfs/k8sdata/mqtt
    server: 192.168.1.15
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: pvc-mqtt

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mqtt
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20M

#---
#kind: PersistentVolumeClaim  
#apiVersion: v1  
#metadata:  
#  name: pvc-mqtt
#  labels: 
#    app: mqtt
#  annotations:
#    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
#spec:  
#  accessModes:
#    - ReadWriteMany
#  resources:
#    requests:
#      storage: 20Mi

