---
apiVersion: v1
kind: Service
metadata:
  name: mqtt
spec:
  ports:
  - name: port1883
    protocol: TCP
    port: 1883
    targetPort: 1883
    nodePort: 31883
  selector:
    app: mqtt
  type: NodePort
