apiVersion: v1
kind: Service
metadata:
  name: mqtt
  labels:
    app: mqtt
spec:
  selector:
    app: mqtt
  ports:
  - name: mqtt
    protocol: TCP
    port: 1883
    targetPort: 1883
    nodePort: 31883
  type: NodePort
