# replace  192.168.1.15 with the fixed IP of your NFS server
# replace  /home/pi/nfs/k8sdata with the path to your NFS server folder

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-deconz
spec:
  capacity:
    storage: 20M
  accessModes:
    - ReadWriteOnce    #volume can be mounted as RW by single node
  nfs:
    path: /home/pi/nfs/k8sdata/deconz
    server: 192.168.1.15
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: pvc-deconz

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-deconz
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20M
