---
apiVersion: v1
kind: Service
metadata:
  name: deconz
  labels:
    app: deconz
spec:
  selector:
    app: deconz
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: ssh
    port: 443
    protocol: TCP
    targetPort: 443
  type: LoadBalancer
#  clusterIP: None



