apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mysite-wordpress-ingress
  namespace: wordpress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - secretName: mysite-tls
      hosts:
        - uk.YOURDOMAIN.com
  rules:
  - host: uk.YOURDOMAIN.com
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: wordpress
              port:
                number: 80
