# replace  192.168.1.15 with the fixed IP of your NFS server
# replace  /home/pi/nfs/k8sdata with the path to your NFS server folder

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-wordpress
  namespace: wordpress
spec:
  capacity:
    storage: 300M
  accessModes:
    - ReadWriteOnce    #volume can be mounted as RW by single node
  nfs:
    path: /home/pi/nfs/k8sdata/wordpress
    server: 192.168.1.15
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: wordpress
    name: pvc-wordpress

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-wordpress
  namespace: wordpress
  labels:   
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300M

