#  kubectl create namespace wordpress

# run the following command to encode your secret for DEV/TEST :
# echo "YOUR_PASSWORD" -n | base64-encoded

---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-pass
  namespace: wordpress
  labels:
    app: wordpress
data:
  # This value is base64-encoded. Do not use this password in production!
  password: YOUR_BASE64_ENCODED_PASSWORD


