# replace 192.168.1.15 with the IP of your MQTT broker and InfluxDB
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mqtt2influx
  name: mqtt2influx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt2influx
  template:
    metadata:
      labels:
        app: mqtt2influx
    spec:
      containers:
      - image: mortyone/mqtt2influx:latest
        name: mqtt2influx
        imagePullPolicy: Always
        ports:
          - name: influx
            containerPort: 8086
          - name: mqtt
            containerPort: 1883
        env:
          - name: LOGGING_LEVEL
            value: "INFO"
          - name: INFLUX_SERVER
            value: "192.168.1.15"    # ← replace with your InfluxDB IP
          - name: INFLUX_PORT
            value: "8086"
          - name: INFLUX_DB
            value: "sensors"
          - name: INFLUX_USER
            valueFrom:
              secretKeyRef:
                name: influx-pass
                key: username
          - name: INFLUX_PASS
            valueFrom:
              secretKeyRef:
                name: influx-pass
                key: password
          - name: MQTT_SERVER
            value: "192.168.1.15"    # ← replace with your MQTT broker IP
          - name: MQTT_PORT
            value: "1883"            # ← replace with your MQTT broker port
          - name: MQTT_USER
            valueFrom:
              secretKeyRef:
                name: mqtt-pass
                key: username
          - name: MQTT_PASS
            valueFrom:
              secretKeyRef:
                name: mqtt-pass
                key: password
        volumeMounts:
          - name: config-file
            mountPath: /config
      volumes:
        - name: config-file
          configMap:
            name: cm-mqtt2influx
