# run the following command to encode your password for DEV :
# echo "YOUR_PASSWORD" -n | base64
---
apiVersion: v1
kind: Secret
metadata:
  name: mqtt-pass
  labels:
    app: mqtt2influx
data:
  # This value is base64-encoded. Do not use this password in production!
  password: YOUR_BASE64_ENCRYPTED_PASSWORD 

---
apiVersion: v1
kind: Secret
metadata:
  name: influx-pass
  labels:
    app: mqtt2influx
data:
  # This value is base64-encoded. Do not use this password in production!
  password: YOUR_BASE64_ENCRYPTED_PASSWORD 


