apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ddns-mortylabs
spec:
  schedule: "*/15 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: unifi
            image: docker.io/curlimages/curl:latest
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - curl -s -u ${GOOGLE_USER}:${GOOGLE_PASS} "https://domains.google.com/nic/update?hostname=unifisa.mortylabs.com"
            envFrom:
            - secretRef:
                name: ddns-secret-mortylabs-unifi

          - name: ha
            image: docker.io/curlimages/curl:latest
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - curl -s -u ${GOOGLE_USER}:${GOOGLE_PASS} "https://domains.google.com/nic/update?hostname=hasa.mortylabs.com"
            envFrom:
            - secretRef:
                name: ddns-secret-mortylabs-ha

          restartPolicy: OnFailure

