apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ddns--pihole
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: uk
            image: docker.io/curlimages/curl:latest
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - curl -s -u ${GOOGLE_USER}:${GOOGLE_PASS} "https://domains.google.com/nic/update?hostname=uk.YOUR_DOMAIN.com"
            envFrom:
            - secretRef:
                name: ddns-secret-uk

          - name: unifi
            image: docker.io/curlimages/curl:latest
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - curl -s -u ${GOOGLE_USER}:${GOOGLE_PASS} "https://domains.google.com/nic/update?hostname=unifi.YOUR_DOMAIN.com"
            envFrom:
            - secretRef:
                name: ddns-secret-unifi

          - name: ha
            image: docker.io/curlimages/curl:latest
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - curl -s -u ${GOOGLE_USER}:${GOOGLE_PASS} "https://domains.google.com/nic/update?hostname=ha.YOUR_DOMAIN.com"
            envFrom:
            - secretRef:
                name: ddns-secret-ha
                
          - name: grafana
            image: docker.io/curlimages/curl:latest
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - curl -s -u ${GOOGLE_USER}:${GOOGLE_PASS} "https://domains.google.com/nic/update?hostname=grafana.YOUR_DOMAIN.com"
            envFrom:
            - secretRef:
                name: ddns-secret-grafana

          - name: pihole
            image: docker.io/curlimages/curl:latest
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - curl -s -u ${GOOGLE_USER}:${GOOGLE_PASS} "https://domains.google.com/nic/update?hostname=pihole.YOUR_DOMAIN.com"
            envFrom:
            - secretRef:
                name: ddns-secret-pihole
          restartPolicy: OnFailure
