apiVersion: apps/v1
kind: Deployment
metadata:
  name: domoticz-deployment
  labels:
    app: domoticz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: domoticz
  template:
    metadata:
      labels:
        app: domoticz
    spec:
      volumes:
      - name: volume100
        persistentVolumeClaim:
          claimName: pvc-domoticz
      containers:
      - name: domoticz
        image: demydiuk/domoticz
        ports:
          - containerPort: 8080
        volumeMounts:
        - name: volume100
          mountPath: /config
          subPath: config
        - name: volume100
          mountPath: /opt/domoticz/scripts/lua
          subPath: lua
 
---
apiVersion: v1
kind: Service
metadata:
  name: domoticz-service
spec:
  selector:
    app: domoticz
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8080
      nodePort: 30001
    
