apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-localhost-domoticz 
  namespace: default   
spec:
  capacity:
    storage: 400M 
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/pi/kubedata/domoticz

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-domoticz
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 400M
  storageClassName: ""


